language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - env: TOXENV=isort
    - env: TOXENV=flake8
    - env: TOXENV=flake8-doc
    - env: TOXENV=black
install:
  - pip install tox
script:
  - tox